### ISSUE TITLE
[BUG] ISA sheets not displayed AND needs extremely CPU usage?

### ISSUE THREAD

**Issue by frsommer** [nfdi4plants/ARCitect#216] opened 2024-07-11 08:01 UTC
**OS and framework information (please complete the following information):**
 - OS: Windows 10

**Describe the bug**
- CPU is extremely busy when opening an ARC
- Downloading ARC, open Assay, try to modify/change an swate-sheet, shows blank window, 
- need to change to an other assay to get something on the screen again,
- it is even that busy thet the snipping tool needs forever to be started... ] A clear and concise description of what the bug is
- [ ] Steps to reproduce
- [ 
![image](https://github.com/nfdi4plants/ARCitect/assets/97098130/8d5237ae-040f-409e-bdb7-adaf8b417add)

![image](https://github.com/nfdi4plants/ARCitect/assets/97098130/80c15ee6-24eb-430c-8985-592d004c688a)

] Screenshots
- [ ] Expected behavior
- [ ] Ideas for solution

**Comment by frsommer** [comment] 2024-07-11 08:04
BTW
Workaround is using version 0.35

**Comment by Freymaurer** [comment] 2024-07-11 08:35
Can you tell us an ARC on which we can test it?

**Comment by frsommer** [comment] 2024-07-11 10:14
yes, try [Frederik Sommer](https://git.nfdi4plants.org/frsommer)
avatar[rlpTREE_reforestration](https://git.nfdi4plants.org/frsommer/rlpTREE_reforestration)
any other will do as well, do you need an invitation?
but now i get a new error:
![image](https://github.com/nfdi4plants/ARCitect/assets/97098130/87f134ea-5d63-4960-830a-1a6a2a22bd95)

**Comment by frsommer** [comment] 2024-07-11 10:44
Hei,
`maybe i did something stupid?:
i sometimes create a new assay or study from the arcitect,
when filling the new isa files i sometimes open the new isa in excel, 
open an old isa and copy some old sheets to the new one, 
modify using old swate and 
saving them

then open in the arcitect and fill the ontologies to have a green check.

that was my workaround for not being able to reuse already written isa files

that worked fine in v35 maybe this is now a problem? (using excel and old swate)

but cannot do anything now since it always throws the error above

**Comment by Freymaurer** [comment] 2024-07-11 11:17
@frsommer i would need an invite (https://git.nfdi4plants.org/frey1)

**Comment by Freymaurer** [comment] 2024-07-11 13:30
Okay, i checked the ARC:

> but now i get a new error:

This was an issue with the database, resolved by @Zerskk ❤️ 

> Downloading ARC, open Assay, try to modify/change an swate-sheet, shows blank window,

This issue is due to some underlying changes in our core code (ARCtrl). Swate was not yet ready for the change but had to implement it for other features. This issue will be resolved in the next Swate update (tonight, or tomorrow).

Swate cannot display `Input/Output [Data]` currently. Again, this will be fixed soon

> CPU is extremely busy when opening an ARC

This issue might be related to #215 on MAC and is currently investigated.

Sadly, it is difficult to narrow down, as we are currently not able to reproduce the performance issue:

![image](https://github.com/nfdi4plants/ARCitect/assets/39732517/c7c2c522-6bcd-4954-96e2-74d141c21017)

**Comment by HLWeil** [comment] 2024-09-09 12:21
Hey @frsommer, does this problem still persist with the current version of ARCitect (0.0.41)?

**Comment by JonasLukasczyk** [comment] 2024-09-24 08:48
I guess the newest ARCtrl and SWATE versions solved this issue. Please feel free to reopen the issue.

**Closed by JonasLukasczyk** 2024-09-24 08:48 UTC
Labels: Type: Bug
