### ISSUE TITLE
[BUG] ARCitect logs out automatically? 

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/ARCitect#72] opened 2023-10-16 11:25 UTC
User: 
> ARCitect user logs out after a while, have to restart ARCitect again

- version 0.0.10
- macOS

**Comment by Brilator** [comment] 2023-11-02 08:22
Possibly fixed by increasing token expiration time.
Needs to be tested though: this was token at key cloak, not gitlab.

**Comment by JonasLukasczyk** [comment] 2024-02-13 13:53
Can we close this? I think this is not a bug.

**Closed** 2024-02-28 10:44 UTC
