### ISSUE TITLE
[Feature Request] Upload/commit procedure unclear, must be improved

### ISSUE THREAD

**Issue by Hannah-Doerpholz** [nfdi4plants/ARCitect#64] opened 2023-10-13 12:22 UTC
**Is your feature request related to a problem? Please describe.**
When I create an ARC I can upload it. Finding the upload option is difficult (as it is under version control). Adding a tab in the left sidebar would be nice. Also, two buttons "commit" and "upload" is confusing. When I click "upload" it should first do the commits and then upload. For users not familiar with git language this is too confusing.

**Describe the solution you'd like**
* Add an "upload" section in the left sidebar.
* Merge "commit" and "upload" into one option do decrease confusion.

**Comment by Brilator** [comment] 2023-11-02 09:17
True, it's confusing. In arc commander (arc sync), we also do not differentiate between commit and push. 
However, I'd rather try and teach people that part of git concept. That also allows them to work and save locally first.

**Comment by Brilator** [comment] 2023-11-22 17:13
Can we close this? 
From my experience the two-stepped mechanism was not too confusing for users.

**Comment by andreaschrader** [comment] 2023-12-13 11:38
There are definitively users for which the two step process is confusing but the message specifying that the user has first to commit befor uploading helped.

**Comment by JonasLukasczyk** [comment] 2024-01-12 19:02
The problem is always that the more we simplify everything to a specific workflow (commit everything > auto handle LFS -> push everything -> auto merge, ....), the more complicated it becomes to do things that do not follow this strict concept. I think it is preferable to teach a bit of git since users will eventually break out of this this workflow.

I will close this issue for now but we will keep everything in mind to improve the UI and docs to better handle the git workflow.

**Closed by JonasLukasczyk** 2024-01-12 19:02 UTC
