### ISSUE TITLE
[BUG] unpacker error

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/ARCitect#262] opened 2024-09-12 14:51 UTC
A windows user got the following error: 

```
error: remote unpack failed: index-pack abnormal exit
To https://git.nfdi4plants.org/user/ARC.git
! [remote rejected] main -> main (unpacker error)
error: failed to push some refs to 'https://git.nfdi4plants.org/user/ARC.git'
```

Did anyone see this before?
Probably more of a DataHUB rather than ARCitect issue. 
@j-bauer

**Comment by Brilator** [comment] 2024-09-12 15:06
this was pseudonymized on purpose...

**Comment by j-bauer** [comment] 2024-09-12 15:07
Ok, nevermind then :D I will check the logs...

**Comment by Brilator** [comment] 2024-09-23 08:04
I guess you won't want to parse every possible error. 

I'd rather suggest to try and avoid having users run into this at all #264. Would require more communication between the tool devs though (limit was not changed to 100 MB).

**Comment by j-bauer** [comment] 2024-09-23 15:00
@Brilator typo? `not = now`? The limit was changed afaik.

**Comment by Brilator** [comment] 2024-09-23 15:04
yes

**Comment by JonasLukasczyk** [comment] 2024-10-04 09:19
This issue will be closed because it is essentially a duplicate of #264

**Closed by JonasLukasczyk** 2024-10-04 09:19 UTC
Labels: Type: Bug
