### ISSUE TITLE
[Feature Request] ORCID / doi retrieval

### ISSUE THREAD

**Issue by andreaschrader** [nfdi4plants/ARCitect#96] opened 2023-12-13 10:56 UTC
**Is your feature request related to a problem? Please describe.**
User expected that the person details are filled out automatically when providing an ORCID iD or doi of a publication.

**Describe the solution you'd like**
If possible, retrieve informations from ORCID that are public and fill out the person details when an ORCID iD is provided. Similar for a doi of a publication.

**Comment by Brilator** [comment] 2024-01-08 12:51
duplicate of #10 and #62

**Closed by Brilator** 2024-01-08 12:51 UTC
