### ISSUE TITLE
[Feature Request] change the DataHub used

### ISSUE THREAD

**Issue by eik-dahms** [nfdi4plants/ARCitect#56] opened 2023-09-26 11:58 UTC
**Is your feature request related to a problem? Please describe.**
I want to be able to used another DataHub as upload/repository location

**Describe the solution you'd like**
Maybe a Dropdown field above Login where user can choose and or add another DataHub address

**Comment by Hannah-Doerpholz** [comment] 2023-10-13 12:37
Maybe the dropdown menu would fit well in the current (v0.0.10) versions tab in the "Remote" field, where we can upload the ARCs.

**Comment by Brilator** [comment] 2023-10-17 12:31
I guess this needs to be tackled two-fold:
1. Login to one selected datahub
2. Be able to re-route (e.g. push to) another datahub / remote #31

**Comment by Hannah-Doerpholz** [comment] 2023-10-25 08:53
I see. Still, it is not that convenient for users that are not logged in/that haven't configured their login credentials locally, since they always need to manually type in repo destination. We have tried uploading to our group name (Usadellab) and that seems to work without first uploading to the personal user account. To do this, we manually edited the correct location name. I am not sure if this is expected behavior though.

**Comment by Brilator** [comment] 2023-10-25 08:58
Yes, this wasn't supposed to be a good solution, but something that works with using ARCitect only (without CLI). 
Alternatively, one could just `git remote set-url origin <new url>`.

**Comment by Brilator** [comment] 2023-10-25 09:02
Cool, I did not know about the solution you describe. This worked, but assumes that an ARC is shared with the group to begin with. 
It's more complicated, if you created and transferred an ARC. That's where users ran into issues.

**Comment by Brilator** [comment] 2023-11-22 16:44
The workarounds don't work anymore. 
ARCitect now always overwrites with default namespace. :(

**Comment by Freymaurer** [comment] 2023-12-19 17:17
This should be solved since 0.0.24!

**Closed** 2023-12-19 17:17 UTC
Labels: Critical

**Comment by eik-dahms** [comment] 2023-12-21 12:01
Where can I change the remote datahub now? 

I used 0.0.24, but I can not find the setting where I can change the remote. 

I tried changing the remote field under versions, which did not work.

Maybe I was looking in the wrong place?

**Comment by Freymaurer** [comment] 2023-12-21 12:15
@JonasLukasczyk

**Comment by Freymaurer** [comment] 2023-12-21 12:45
This should be it @eik-dahms :

![image](https://github.com/nfdi4plants/ARCitect/assets/39732517/e2694890-636d-4f06-b490-dd3aa5d71f07)
